export type EmbedderProvider = "hash" | "openai" | "ollama";

/** process.env keys (PI_MEMORY_*). */
export const ENV_KEYS = {
  EMBEDDER: "PI_MEMORY_EMBEDDER",
  EMBED_DIM: "PI_MEMORY_EMBED_DIM",
  OPENAI_API_KEY: "PI_MEMORY_OPENAI_API_KEY",
  OPENAI_EMBED_MODEL: "PI_MEMORY_OPENAI_EMBED_MODEL",
  OLLAMA_BASE_URL: "PI_MEMORY_OLLAMA_BASE_URL",
  OLLAMA_EMBED_MODEL: "PI_MEMORY_OLLAMA_EMBED_MODEL",
  OLLAMA_LLM_BASE_URL: "PI_MEMORY_OLLAMA_LLM_BASE_URL",
  OLLAMA_LLM_MODEL: "PI_MEMORY_OLLAMA_LLM_MODEL",
  HELPER_MODEL: "PI_MEMORY_HELPER_MODEL",
  HELPER_API_KEY: "PI_MEMORY_HELPER_API_KEY",
  OPENAI_COMPAT_BASE_URL: "PI_MEMORY_OPENAI_COMPAT_BASE_URL",
  OPENAI_COMPAT_MODEL: "PI_MEMORY_OPENAI_COMPAT_MODEL",
  OPENAI_COMPAT_API_KEY: "PI_MEMORY_OPENAI_COMPAT_API_KEY",
  HTTP_TIMEOUT_MS: "PI_MEMORY_HTTP_TIMEOUT_MS",
  PREFLIGHT_TIMEOUT_MS: "PI_MEMORY_PREFLIGHT_TIMEOUT_MS",
  REINDEX_DEBOUNCE_MS: "PI_MEMORY_REINDEX_DEBOUNCE_MS",
  CONSOLIDATE_DEBOUNCE_MS: "PI_MEMORY_CONSOLIDATE_DEBOUNCE_MS",
  AGENT_DIR: "PI_MEMORY_AGENT_DIR",
  ENV_FILE: "PI_MEMORY_ENV_FILE",
} as const;

/** Fallback OPENAI_API_KEY when PI_MEMORY_OPENAI_API_KEY unset. */
export const FALLBACK_OPENAI_API_KEY_ENV = "OPENAI_API_KEY";

export const DEFAULT_EMBEDDER: EmbedderProvider = "hash";
export const DEFAULT_OPENAI_EMBED_MODEL = "text-embedding-3-small";
export const DEFAULT_OLLAMA_BASE_URL = "http://127.0.0.1:11434";
export const DEFAULT_OLLAMA_EMBED_MODEL = "nomic-embed-text";

export const DEFAULT_HELPER_PROVIDER = "deepseek";
export const DEFAULT_HELPER_MODEL = "deepseek-v4-flash";
export const DEFAULT_HELPER_MODEL_SPEC = `${DEFAULT_HELPER_PROVIDER}/${DEFAULT_HELPER_MODEL}`;

export const DEFAULT_EMBED_DIM_FALLBACK = 1536;

/** Known embedding dimensions; override with PI_MEMORY_EMBED_DIM if needed. */
export const KNOWN_EMBED_DIMS: Record<string, number> = {
  "text-embedding-3-small": 1536,
  "text-embedding-3-large": 3072,
  "nomic-embed-text": 768,
  "mxbai-embed-large": 1024,
  "all-minilm": 384,
};

export const DEFAULT_HASH_EMBED_DIM = 768;
